server:
  port: 10002
spring:
  application:
    name: web-service
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_auth?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
#  activemq:
#    broker-url: tcp://127.0.0.1:61616
#    in-memory: false
#    user: admin
#    password: admin
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
  instance:
    prefer-ip-address: true