server:
  port: 10001
spring:
  application:
    name: eureka-web-server
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
